nidirect_search.solr_elevated_id.*:
  type: config_entity
  label: solr_elevated_ids
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    nodes:
      type: string
      label: 'Nodes'
    uuid:
      type: string
