<?php

/**
 * @file
 * Contains nidirect_gp.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nidirect_gp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nidirect_gp module.
    case 'help.page.nidirect_gp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('NI Direct GP') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nidirect_gp_theme() {
  return [
    'nidirect_gp' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function nidirect_gp_preprocess_node(&$variables) {
  $node = &$variables['node'];
  if ($node->bundle() != 'gp_practice' || $variables['view_mode'] != 'teaser') {
    return;
  }

  // Lead GP.
  if (!empty($node->field_gp_practice_lead->referencedEntities())) {
    $gp = $node->field_gp_practice_lead->referencedEntities()[0];
    $variables['gp_names'][] = $gp->label();
  }

  // Member GPs.
  if (!empty($node->field_gp_practice_member->referencedEntities())) {
    foreach ($node->field_gp_practice_member->referencedEntities() as $index => $gp) {
      $variables['gp_names'][] = $gp->label();
    }
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function nidirect_gp_entity_extra_field_info() {
  $extra['node']['gp_practice']['display']['gp_names'] = [
    'label' => t('GP names'),
    'description' => t('List of GP names, lead GP listed first.'),
    'weight' => 0,
  ];

  return $extra;
}

/**
 * Implements hook_preprocess_block().
 */
function nidirect_gp_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'views_exposed_filter_block:gp_practices-find_a_gp') {
    $variables['content']['preamble'] = [
      '#markup' => '<p>' . t('Enter a GP name, practice or town.') . '</p>',
      '#weight' => -10,
    ];
  }
}
