<?php

/**
 * @file
 * Hook functions for nidirect_site_themes module.
 */

/**
 * Implements hook_preprocess_item_list().
 *
 * We use this to manipulate the taxonomy manager options. it doesn't
 * use form API to generate this list so by preprocessing the theme item
 * it uses, we can very, very selectively prune off the vocabs the user
 * isn't allowed to access.
 *
 * Anything more substantial, we probably need to re-route the request
 * to our own controller class.
 */
function nidirect_site_themes_preprocess_item_list(&$variables) {
  if (\Drupal::routeMatch()->getRouteName() != 'taxonomy_manager.admin') {
    return;
  }

  foreach ($variables['items'] as $index => $item) {
    // Extract the term id from the URL (that's all we have to work with at this level).
    $matches = [];
    preg_match('#\/admin\/structure\/taxonomy_manager\/voc/(.+)\"#', $item['value']->getGeneratedLink(), $matches);
    $vocab_id = $matches[1];

    if (\Drupal::currentUser()->hasPermission('edit terms in ' . $vocab_id) == FALSE) {
      unset($variables['items'][$index]);
    }
  }
}

/**
 * Implements hook_page_attachments().
 */
function nidirect_site_themes_page_attachments(array &$attachments) {
  // Attach extra custom css for admin menu.
  $attachments['#attached']['library'][] = 'nidirect_site_themes/admin_theme.css';
}
