field.value.nidirect_cold_weather_period:
  type: string
  label: 'Default value'
  mapping:
    date_start:
      type: string
      label: 'Value'
    date_end:
      type: string
      label: 'Value'
    stations:
        type: string
        label: 'Value'
