nidirect_cold_weather_payments.weather_station.*:
  type: config_entity
  label: 'Weather station config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'label'
    postcodes:
      type: string
      label: 'Postcodes'
    uuid:
      type: string
