<?php

/**
 * @file
 * Contains nidirect_taxoman.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nidirect_taxoman_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nidirect_taxoman module.
    case 'help.page.nidirect_taxoman':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage your large taxonomies') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nidirect_taxoman_theme() {
  return [
    'nidirect_taxoman' => [
      'render element' => 'children',
    ],
  ];
}
