# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2

jobs:
  # Test that coding standards fit drupal.org definitions.
  coding_standards:
    docker:
      - image: circleci/php:7.4.15-apache-browsers
    steps:
      - checkout
      - run:
          name: Fetch phpcs and dependencies
          command: |
            composer require drupal/coder --prefer-stable --no-interaction --optimize-autoloader
            # Move vendor directory up a level as we don't want to code-check all of that.
            mv vendor ../
      - run:
          name: Fetch phpcs convenience script
          command: |
            curl https://raw.githubusercontent.com/dof-dss/nidirect-drupal/main/phpcs.sh -o /home/circleci/project/phpcs.sh
            chmod +x /home/circleci/project/phpcs.sh
      - run:
          name: PHPCS analysis
          command: /home/circleci/project/phpcs.sh /home/circleci "/home/circleci/project"

  deprecated_code:
    docker:
      - image: circleci/php:7.4.15-apache-browsers
    steps:
      - checkout:
          path: /home/circleci/nidirect-site-modules
      - run:
          name: Add OS and PHP extensions/config
          command: |
            sudo cp /home/circleci/nidirect-site-modules/.circleci/docker-php-circleci.ini /usr/local/etc/php/conf.d/
            sudo apt-get update
            sudo apt-get install -y libpng-dev
            sudo docker-php-ext-install gd
      - run:
          name: Fetch latest Drupal version
          command: |
            cd /home/circleci
            composer create-project drupal-composer/drupal-project:8.x-dev /home/circleci/project --no-interaction
      - run:
          name: Download dependent contrib modules.
          command: |
            cd /home/circleci/project
            composer require drupal/webform drupal/linkit:^6.0 mglaman/drupal-check --no-interaction
      - run:
          name: Move custom code into position
          command: mv /home/circleci/nidirect-site-modules /home/circleci/project/web/modules/custom
      - run:
          name: Deprecated code check
          command: |
            cd /home/circleci/project/web
            ../vendor/bin/drupal-check modules/custom -e "*/tests/*"

workflows:
  version: 2
  static-analysis:
    jobs:
      - coding_standards
      - deprecated_code
