# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2

jobs:
  # Test that coding standards fit drupal.org definitions.
  coding_standards:
    docker:
      - image: circleci/php:7.3.14-apache-browsers
    steps:
      - checkout
      - run:
          name: Fetch phpcs and dependencies
          command: |
            composer require drupal/coder --prefer-stable --no-interaction --optimize-autoloader
            # Move vendor directory up a level as we don't want to code-check all of that.
            mv vendor ../
      - run:
          name: Fetch phpcs convenience script
          command: |
            curl https://raw.githubusercontent.com/dof-dss/nidirect-drupal/development/phpcs.sh -o /home/circleci/project/phpcs.sh
            chmod +x /home/circleci/project/phpcs.sh
      - run:
          name: PHPCS static analysis
          command: /home/circleci/project/phpcs.sh /home/circleci "/home/circleci/project"

workflows:
  version: 2
  static-analysis:
    jobs:
      - coding_standards
