version: 2.1

default_docker_image: &docker_image
  docker:
    - image: thecodingmachine/php:8.1-v4-apache-node14
      environment:
        PROJECT_ROOT: "/home/docker/project"
        PHP_EXTENSION_GD: 1
        PHP_INI_MEMORY_LIMIT: 1g

jobs:
  # Test that coding standards fit drupal.org definitions.
  coding_standards:
    <<: *docker_image
    steps:
      - checkout
      - run:
          name: Fetch phpcs and dependencies
          command: |
            composer require drupal/coder --prefer-stable --no-interaction --optimize-autoloader
            # Move vendor directory up a level as we don't want to code-check all of that.
            mv vendor ../
      - run:
          name: Fetch phpcs convenience script
          command: |
            curl https://raw.githubusercontent.com/dof-dss/nidirect-drupal/development/phpcs.sh -o $PROJECT_ROOT/phpcs.sh
            chmod +x $PROJECT_ROOT/phpcs.sh
      - run:
          name: PHPCS analysis
          command: $PROJECT_ROOT/phpcs.sh ~/ "${PROJECT_ROOT}"

  deprecated_code:
    <<: *docker_image
    steps:
      - checkout:
          path: ~/nidirect-site-modules
      - run:
          name: Fetch main project composer manifest and extend as required.
          command: |
            cd $PROJECT_ROOT
            wget https://raw.githubusercontent.com/dof-dss/nidirect-drupal/development/composer.json
            # Remove dof-dss packages (from the requires section, not the scaffold).
            sed -i -E '/dof-dss\/.+:/d' composer.json
            # NB: no lock file fetched, and some packages aren't explicit dependencies/versions
            # so we add them here to make sure they arrive with the rest listed in composer.json.
            composer require -n mglaman/drupal-check drupal/clientside_validation:3.0.0-rc4 maxh/php-nominatim:^2.3
      - run:
          name: Move custom code into position
          command: mv ~/nidirect-site-modules $PROJECT_ROOT/web/modules/custom
      - run:
          name: Deprecated code check
          command: |
            cd $PROJECT_ROOT/web
            ../vendor/bin/drupal-check modules/custom

workflows:
  version: 2
  static-analysis:
    jobs:
      - coding_standards
      - deprecated_code
