<?php

/**
 * @file
 * Contains nidirect_breadcrumbs.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function nidirect_breadcrumbs_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  foreach (array_keys($form['actions']) as $action) {
    if ($action === 'preview') {
      $form['actions'][$action]['#submit'][] = 'nidirect_breadcrumbs_preview_cache_handler';
    }
  }
}

/**
 * Invalidates the node:uuid cache to ensure we get accurate previews.
 *
 * If the Theme/subtheme field has changed and the user requests a preview
 * the breadcrumb builder will not be called after the initial preview, we
 * need to force a rebuild by invalidating the node:uuid cache.
 *
 * @param array $form
 *   Form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state object.
 */
function nidirect_breadcrumbs_preview_cache_handler(array &$form, FormStateInterface $form_state) {
  if ($form_state->getFormObject() instanceof EntityFormInterface) {
    $route = $form_state->getRedirect();

    $uuid = $route->getRouteParameters()['node_preview'];
    Cache::invalidateTags(['node:' . $uuid]);
  }

}

/**
 * Implements hook_preprocess_breadcrumb().
 */
function nidirect_breadcrumbs_preprocess_breadcrumb(&$variables) {
  // Check for missing breadcrumb on nodes.
  // If a node is found to have a missing breadcrumb, log a warning and
  // prevent further checks being made.

  if (\Drupal::state()->get('missing_breadcrumb_check') !== 1) {
    $route_match = \Drupal::routeMatch();
    if ($route_match->getRouteName() == 'entity.node.canonical') {
      $node = $route_match->getParameter('node');
      if (empty($variables['breadcrumb'])) {
        \Drupal::logger('nidirect_breadcrumbs')
          ->warning('Breadcrumb missing for node @node', ['@node' => $node->id()]);
        \Drupal::state()->set('missing_breadcrumb_check', 1);

        // @TODO add code to help debug why breadcrumb is missing for this node.
      }
    }
  }
}
