<?php

/**
 * @file
 * Contains nidirect_backlinks.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nidirect_backlinks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nidirect_backlinks module.
    case 'help.page.nidirect_backlinks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('NI Direct backlinks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 */
function nidirect_backlinks_entity_insert(EntityInterface $entity) {
  // \Drupal::service('nidirect_backlinks.linkmanager')->processEntity($entity);
}

/**
 * Implements hook_entity_update().
 */
function nidirect_backlinks_entity_update(EntityInterface $entity) {
  // \Drupal::service('nidirect_backlinks.linkmanager')->processEntity($entity);
}

/**
 * Implements hook_entity_delete().
 */
function nidirect_backlinks_entity_delete(EntityInterface $entity) {
  \Drupal::service('nidirect_backlinks.linkmanager')->deleteEntity($entity);
}
