<?php

/**
 * @file
 * Contains nidirect_password_policy.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function nidirect_password_policy_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $pwd_form_ids = ['user_register_form', 'user_form'];

  if (in_array($form_id, $pwd_form_ids)) {
    $form['#validate'][] = 'nidirect_password_policy_validate_password';
  }
}

/**
 * Validation callback for user forms.
 */
function nidirect_password_policy_validate_password(array &$form, FormStateInterface &$form_state) {
  $pwd_element = &$form['account']['pass'];
  $pwd = $form_state->getValue('pass');

  if (!empty($pwd)) {
    // Minimum 10 chars.
    if (strlen($pwd) <= 10) {
      $form_state->setError($pwd_element, t('Password must be at least 10 characters long.'));
    }

    // Characters: 1 uppercase letter.
    if (!preg_match('/([A-Z])+/', $pwd)) {
      $form_state->setError($pwd_element, t('Password must contain at least one uppercase character.'));
    }

    // Characters: 1 lowercase letter.
    if (!preg_match('/([a-z])+/', $pwd)) {
      $form_state->setError($pwd_element, t('Password must contain at least one lowercase character.'));
    }

    // Characters: 1 numerical character.
    if (!preg_match('/\d+/', $pwd)) {
      $form_state->setError($pwd_element, t('Password must contain at least one numerical character.'));
    }

    // Characters: 1 special character.
    if (!preg_match('/([^A-Za-z0-9])+/', $pwd)) {
      $form_state->setError($pwd_element, t('Password must contain at least one non-numerical and non-alphabetical character.'));
    }

    // Username: cannot match (case insensitive).
    $username = $form_state->getValue('name');
    if (preg_match('/' . $username . '/i', $pwd)) {
      $form_state->setError($pwd_element, t('Password must not contain your username.'));
    }
  }
}
