<?php

/**
 * @file
 * Contains nidirect_webforms.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nidirect_webforms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nidirect_webforms module.
    case 'help.page.nidirect_webforms':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Weform handlers and components') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nidirect_webforms_theme() {
  return [
    'nidirect_webforms' => [
      'render element' => 'children',
    ],
  ];
}
