<?php

/**
 * @file
 * Contains nidirect_webforms.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nidirect_webforms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nidirect_webforms module.
    case 'help.page.nidirect_webforms':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Weform handlers and components') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nidirect_webforms_theme() {
  return [
    'nidirect_webforms_quiz_results' => [
      'render element' => 'children',
      'variables' => [
        'introduction' => NULL,
        'result' => NULL,
        'feedback_introduction' => NULL,
        'feedback' => [],
        'score' => 0,
        'max_score' => 0,
        'pass_score' => 0,
        'passed' => NULL,
      ],
    ],
    'nidirect_webforms_quiz_answer_feedback' => [
      'render element' => 'children',
      'variables' => [
        'title' => NULL,
        'question' => NULL,
        'feedback' => NULL,
        'passed' => NULL,
      ],
    ],
  ];
}
