<?php

/**
 * @file
 * Contains nidirect_news.module.
 */

use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\taxonomy\TermInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess_field().
 */
function nidirect_news_preprocess_field(array &$variables) {
  $entity_type = $variables['entity_type'];
  $bundle = $variables['element']['#bundle'];
  $field_name = $variables['field_name'];
  $view_mode = $variables['element']['#view_mode'];

  if ($field_name != 'field_published_date') {
    return;
  }

  if ($entity_type != 'node' || $bundle != 'news' || $view_mode != 'full') {
    return;
  }

  // Adjust the title in full display mode to match present site value.
  $variables['label'] = t('Date published');
}

/**
 * Implements hook_preprocess_node().
 */
function nidirect_news_preprocess_node(array &$variables) {
  if ($variables['node']->getType() == 'featured_content_list') {
    if ($variables['view_mode'] == 'full' && !empty($variables['node']->field_tags->target_id)) {
      $news_tag = \Drupal::entityTypeManager()
        ->getStorage('taxonomy_term')
        ->loadByProperties(['name' => 'News']);
      $news_tag = reset($news_tag);

      if ($variables['node']->field_tags->target_id == $news_tag->id()) {
        // Replace the node view with a rendered view display, using the node
        // items as arguments. This mirrors the display you would see on the
        // embedded views display.
        $variables['content'] = \Drupal::service('nidirect_news.news')->getFeaturedNews();
      }
    }
  }
}
