<?php

/**
 * @file
 * module file.
 */

/**
 * Implements hook_theme().
 */
function nidirect_custom_blocks_theme() {
  return [
    'nidirect_sharing' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK()
 */
function nidirect_custom_blocks_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'nidirect_sharing') {
    $variables['#attached']['library'][] = 'nidirect_custom_blocks/nidirect_sharing';
  }
}
