<?php

/**
 * @file
 * module file.
 */

/**
 * Implements hook_theme().
 */
function nidirect_custom_blocks_theme() {
  return [
    'nidirect_sharing' => [
      'variables' => [
        'content' => NULL,
        'fb_link' => 'https://www.facebook.com/dialog/share?app_id=5303202981&display=popup&href=http%3A%2F%2Fnidirect8.local%3A8080%2Farticles%2Fbaking-with-your-child&redirect_uri=https%3A%2F%2Fstatic.addtoany.com%2Fmenu%2Fthanks.html%23url%3Dhttp%3A%2F%2Fnidirect8.local%3A8080%2Farticles%2Fbaking-with-your-child&quote=',
        'tw_link' => 'https://twitter.com/intent/tweet?text=Hello%20world',
        'mail_link' => 'mailto:?subject=Shared%20from%20nidirect.gov.uk&body=Baking%20with%20your%20child'
      ],
      'render element' => 'children',
    ],
  ];
}
