<?php

/**
 * @file
 * module file.
 */

/**
 * Implements hook_theme().
 */
function nidirect_custom_blocks_theme() {
  return [
    'nidirect_sharing' => [
      'variables' => [
        'content' => NULL,
        'fb_link' => 'https://www.facebook.com/dialog/share?app_id=5303202981&display=popup&href=http%3A%2F%2Fnidirect8.local%3A8080%2Farticles%2Fbaking-with-your-child&redirect_uri=https%3A%2F%2Fstatic.addtoany.com%2Fmenu%2Fthanks.html%23url%3Dhttp%3A%2F%2Fnidirect8.local%3A8080%2Farticles%2Fbaking-with-your-child&quote=',
      ],
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK()
 */
function nidirect_custom_blocks_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'nidirect_sharing') {
    $variables['#attached']['library'][] = 'nidirect_custom_blocks/nidirect_sharing_css';
    $variables['#attached']['library'][] = 'nidirect_custom_blocks/nidirect_sharing_js';
  }
}
